import '@styles/globals.css'
import { Inter, Inconsolata } from 'next/font/google'

//Components
import Navbar from '@components/Navbar'
import Footer from '@components/Footer'
import Sidebar from '@components/Sidebar'
import SideMenu from '@components/SideMenu'

const inter = Inter({ subsets: ['latin'] })
const inconsolata = Inconsolata({ subsets: ['latin', 'latin-ext'], weights: ['400', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inconsolata.className + " bg-vs-gray-6 min-h-[100vh]"}>
        <Navbar/>
        <Sidebar/>
        <SideMenu/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
